server:
  port: 8084

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

####### resource server configuration properties
spring:
  cloud:
    gateway:
      routes:
        - id: projects_route
          uri: http://localhost:8081
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/(?<segment>.*), /lsso-project-resource-server/api/$\{segment}
        - id: tasks_route
          uri: http://localhost:8085
          predicates:
            - Path=/tasks/**
          filters:
            - RewritePath=/(?<segment>.*), /lsso-task-resource-server/api/$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8082"
            allowedHeaders:
              - Content-Type
            allowedMethods:
              - GET
              - POST
