server:
  port: 8085
  servlet:
    context-path: /lsso-task-resource-server

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  devtools:
    livereload:
      port: 35731
