spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9003"
      client:
        registration:
          client-app:
            provider: spring
            client-id: "client-app"
            client-secret: "12345"
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/client-app
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9003"