spring.application.name: my-spring-resource-server


server:
  port: 8081
  servlet:
    context-path: /lsso-resource-server


############## resource server configuration properties ###############################
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/baeldung
          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
  devtools:
    livereload:
      port: 35730
