server:
  port: 9001

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: my-oauth-server

  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          client-app:
            registration:
              client-id: "client-app"
              client-secret: "{noop}12345"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/client-app"
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false